version: '2'

services:
  node:
    build:
      context: ./
    image: wmde/less-variable-resolver
    volumes:
      - '~/.npm:/.npm'
      - './:/app'
    working_dir: /app
    environment:
      - NODE_ENV
      - NODE_DEBUG